version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: hon-mysql
    restart: always
    environment:
      MYSQL_DATABASE: HON_DB
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: hon-app
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/HON_DB
      DB_PASSWORD: ${DB_PASSWORD}
      jwt.secret-key: ${JWT_SECRET_KEY}
      KMA_SERVICE_KEY: ${KMA_SERVICE_KEY}
      AIRKOREA_SERVICE_KEY: ${AIRKOREA_SERVICE_KEY}
      tour-api.service-key: ${TOUR_API_SERVICE_KEY}
      kakao.rest-api-key: ${KAKAO_REST_API_KEY}

volumes:
  mysql-data: